### ISSUE TITLE
MimeUnrender instance for Servant.HTML.Lucid.HTML?

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-servant/servant-lucid#14]
I think it's required to use `Servant.HTML.Lucid.HTML` with `servant-client`. I can attempt a PR if there is no underlying reason why this instance is not there.

**Comment by saurabhnanda** [comment]
I attempted implementing this, but realised that there is no way to go from a `Data.ByteString.Lazy.UTF8.ByteString` to `Html () :: HtmlT Identity ()`

Am I missing anything here?

**Comment by alpmestan** [comment]
You're not. To get a `MimeUnrender` instance, you essentially need to be backed by an HTML _parsing_ library, like `tagsoup`, `taggy`, `xml-html-conduit` and what not (note that many of those libs have `lens`-based interfaces which makes parsing precise bits of data more bearable that it would seem at first).

**Comment by saurabhnanda** [comment]
@alpmestan is it worth the effort? What would one even do with an `Html ()` value apart from rendering it back to a ByteString or Text? It's not like it's an AST which can be programmatically manipulated.

**Comment by alpmestan** [comment]
@saurabhnanda Well if you were going to parse it, you would at the very least want to get a list of tags or a DOM tree, or a value of a type that you supply that can be built by extracting bits and pieces from the HTML. You'd then not care in the slightest about lucid, which is only concerned about constructing and rendering HTML. It's not like `aeson` where parsing and (efficient) rendering is provided by the same package.

**Comment by phadej** [comment]
> `Data.ByteString.Lazy.UTF8.ByteString` to `Html () :: HtmlT Identity ()`

`toHtmlRaw`

---

That said, I'm really unsure one want to have `Unrender HTML (HtmlT ())`

If you have an API where you both *write* on a server, and *read* in a client, I'd recommend to define a newtype like:

```haskell
newtype MyHtml = MyHtml LBS.ByteString

mkMyHtml :: ToHtml a => a -> MyHtml
mkMyHtml = MyHtml . renderBS

instance MimeRender HTML MyHtml where
  mimeRender _ (MyHtml bs) = bs

instance MimeUnrender HTML MyHtml where
  mimeUnrender _ bs = Right (MyHtml bs)
```

and write APIs using that type.

---

`HtmlT m ()` is a wrong type to read in.

**Comment by georgefst** [comment]
What about:
```
instance MimeUnrender HTML Text where
    mimeUnrender _ = pure . decodeUtf8 . BL.toStrict
```

I've just had to defined this in one of my `servant-client` projects.

There's an argument that it doesn't really belong in this package seeing as it doesn't use Lucid, but it seems preferable to reuse the existing `HTML` definition. And I don't see any harm. Plus, one can _choose_ to use `toHtmlRaw` on the output if required.
