### ISSUE TITLE
Release to support servant 0.18?

### ISSUE THREAD

**Issue by TomMD** [haskell-servant/servant-lucid#17]
Could we get a release to Hackage to support servant 0.18?

**Comment by dmjio** [comment]
Yea, can do it today.

**Comment by TomMD** [comment]
I've heard of a New York minute, which allegedly is much shorter than a west coast minute.  I didn't know a New York day was different as well.

**Comment by dmjio** [comment]
Oops ;) Very easy to lose track of time in the big apple 🍎

**Comment by dmjio** [comment]
https://github.com/haskell-servant/servant-lucid/commit/06aa8219e2febab7fb09b036cd1dd4fcfbad65a1
https://hackage.haskell.org/package/servant-lucid 

[Hackage](https://hackage.haskell.org/package/servant-lucid)
